## Here we will visualize our dataset (images)

In [1]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from keras.preprocessing import image_dataset_from_directory
import tensorflow as tf
import numpy as np
from tensorflow import keras
from pathlib import Path
import cv2

2024-04-29 00:58:14.310585: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:

directory = Path('/Users/ubaydulsami/Desktop/samiStudy/CTP/ctp main program/project-spring2024/dataset').resolve()
image_dataset = keras.utils.image_dataset_from_directory(
    str(directory),
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 971 files belonging to 2 classes.


In [3]:
train_data = tf.keras.preprocessing.image_dataset_from_directory(
    directory,
    validation_split=0.2,
    subset="training",
    seed=123,
)

testing_data = tf.keras.preprocessing.image_dataset_from_directory(
    directory,
    validation_split=0.2,
    subset="validation",
    seed=123,
)

Found 971 files belonging to 2 classes.
Using 777 files for training.
Found 971 files belonging to 2 classes.
Using 194 files for validation.


In [4]:
data = tf.keras.utils.image_dataset_from_directory(directory,batch_size=1,image_size=(256,256))
for x, y in data:
  print("image: {}, label: {}".format(x,y))

Found 971 files belonging to 2 classes.
image: [[[[4.4342041e+00 2.1434204e+01 3.7434204e+01]
   [6.0000000e+00 2.3000000e+01 3.9000000e+01]
   [6.6875000e+00 2.3687500e+01 3.9687500e+01]
   ...
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]]

  [[5.0118408e+00 2.2011841e+01 3.8011841e+01]
   [6.3414307e+00 2.3341431e+01 3.9341431e+01]
   [6.8769531e+00 2.3876953e+01 3.9876953e+01]
   ...
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]]

  [[5.9835205e+00 2.2983521e+01 3.8983521e+01]
   [7.1842041e+00 2.4184204e+01 4.0184204e+01]
   [7.6875000e+00 2.4687500e+01 4.0687500e+01]
   ...
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]
   [3.0000000e+00 1.1000000e+01 2.4000000e+01]]

  ...

  [[1.9375000e+00 1.1937500e+01 2.1937500e+01]
   [0.0000000e+00 1.000000

image: [[[[193.375   203.375   192.375  ]
   [189.65625 195.65625 185.65625]
   [191.125   197.125   187.125  ]
   ...
   [103.84375  85.84375  71.84375]
   [165.125   169.125   155.125  ]
   [157.125   172.375   174.625  ]]

  [[206.28125 210.28125 209.28125]
   [192.125   202.125   192.625  ]
   [182.8125  190.8125  177.8125 ]
   ...
   [102.625    84.625    64.625  ]
   [158.03125 167.03125 146.53125]
   [162.09375 175.09375 168.09375]]

  [[197.28125 207.28125 199.28125]
   [192.34375 202.34375 194.34375]
   [168.96875 182.71875 159.84375]
   ...
   [103.21875  88.21875  67.21875]
   [156.28125 165.28125 144.28125]
   [159.875   170.625   161.875  ]]

  ...

  [[ 66.       59.       43.     ]
   [ 51.96875  51.71875  44.46875]
   [ 56.875    61.875    55.875  ]
   ...
   [ 19.       10.        5.     ]
   [ 18.        9.        4.     ]
   [ 16.625     9.625     1.625  ]]

  [[ 49.4375   43.4375   29.4375 ]
   [ 46.375    46.375    34.375  ]
   [ 49.       50.       43.5    ]
   ..

image: [[[[ 4.501953    3.5019531  17.501953  ]
   [ 1.2026749   0.20267487 15.190956  ]
   [ 2.0696945   1.0696945  17.069695  ]
   ...
   [ 0.          2.0501633  14.559929  ]
   [ 0.          1.0117188  16.011719  ]
   [ 2.140625    1.140625   17.140625  ]]

  [[ 1.0917969   0.58984375 13.59375   ]
   [ 1.8224182   1.8224182  13.822418  ]
   [11.216202   10.216202   24.216202  ]
   ...
   [ 2.0390625   2.0390625  13.83799   ]
   [ 2.4101562   1.4101562  17.410156  ]
   [ 4.5344543   3.5344543  17.534454  ]]

  [[12.062576   11.564529   24.560623  ]
   [ 0.3458023   0.3458023  11.865631  ]
   [12.771103   12.771103   24.460876  ]
   ...
   [12.323929   11.323929   27.323929  ]
   [ 5.3903275   4.3903275  20.390327  ]
   [ 3.          2.         18.        ]]

  ...

  [[ 1.2923508   1.2923508  12.951889  ]
   [ 0.66591644  0.66591644 13.160057  ]
   [ 1.9938202   0.9938202  16.013351  ]
   ...
   [ 1.6835938   0.68359375 16.683594  ]
   [ 4.7420883   3.7420883  19.742088  ]
   [ 1.81

image: [[[[254.       254.       254.      ]
   [254.       254.       254.      ]
   [254.       254.       254.      ]
   ...
   [ 90.85156  153.        96.      ]
   [ 91.07156  149.56375   93.528595]
   [ 89.956696 153.9567    93.956696]]

  [[254.       254.       254.      ]
   [254.       254.       254.      ]
   [254.       254.       254.      ]
   ...
   [121.03958  179.57864  123.80911 ]
   [ 91.71094  153.14453   95.71094 ]
   [ 90.       154.        94.      ]]

  [[254.       254.       254.      ]
   [254.       254.       254.      ]
   [254.       254.       254.      ]
   ...
   [ 90.463684 151.46368   92.463684]
   [ 98.81528  159.81528  100.81528 ]
   [ 90.       154.        94.      ]]

  ...

  [[254.       254.       254.      ]
   [254.85547  253.14453  254.      ]
   [254.       254.       254.      ]
   ...
   [ 91.22006  152.22006   93.22006 ]
   [ 92.       153.        94.      ]
   [ 90.       154.        94.      ]]

  [[254.       254.       254.      ]


image: [[[[192.0218   131.0218    84.021805]
   [194.45428  134.45428   84.454285]
   [196.32506  135.32506   88.32506 ]
   ...
   [143.41565  100.55981   74.03284 ]
   [149.74146  103.262985  77.98068 ]
   [148.6761   103.6761    73.26921 ]]

  [[189.88477  133.27148   86.578125]
   [195.17783  137.53119   87.61443 ]
   [187.39404  129.39404   82.64795 ]
   ...
   [137.97177   97.22568   72.598724]
   [143.29697   99.81429   73.49863 ]
   [142.84486   96.734535  68.983536]]

  [[184.91649  129.34032   83.86571 ]
   [186.10773  132.31255   85.28546 ]
   [180.02179  125.324425  79.51974 ]
   ...
   [136.28845   98.6615    74.54236 ]
   [137.69336   94.114655  71.793236]
   [150.46161  104.46162   78.46162 ]]

  ...

  [[215.70566  133.4337   100.25728 ]
   [162.2746   101.20792   65.52934 ]
   [151.66283   95.90903   60.11215 ]
   ...
   [166.00154  115.8492    67.075554]
   [147.20059   97.15066   65.446686]
   [131.39342   86.35167   62.681374]]

  [[209.8019   139.62706   89.45318 ]


image: [[[[254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]
   ...
   [254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]]

  [[254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]
   ...
   [254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]]

  [[254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]
   ...
   [254. 254. 254.]
   [254. 254. 254.]
   [254. 254. 254.]]

  ...

  [[144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]
   ...
   [144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]]

  [[144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]
   ...
   [144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]]

  [[144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]
   ...
   [144. 144. 144.]
   [144. 144. 144.]
   [144. 144. 144.]]]], label: [1]
image: [[[[5.97241974e+01 8.13525848e+01 9.39658661e+01]
   [3.37996063e+01 5.22421875e+01 7.09144440e+01]
   [2.32207031e+01 4.50891876e+01 5.80468597e+01]
   ...
   [2.52054047e+02 2.46588745e+02 2

image: [[[[211.      212.      204.     ]
   [210.      211.      203.     ]
   [210.      211.      203.     ]
   ...
   [211.94131 208.94131 199.94131]
   [213.      210.      201.     ]
   [213.      210.      201.     ]]

  [[210.86914 211.86914 203.86914]
   [210.      211.      203.     ]
   [207.39258 208.39258 200.39258]
   ...
   [213.      210.      201.     ]
   [213.      210.      201.     ]
   [213.      210.      201.     ]]

  [[210.      211.      203.     ]
   [210.      211.      203.     ]
   [207.      208.      200.     ]
   ...
   [210.      207.      198.     ]
   [210.      207.      198.     ]
   [213.      210.      201.     ]]

  ...

  [[178.23047 176.23047 164.23047]
   [179.1325  177.1325  165.1325 ]
   [183.11523 181.11523 169.11523]
   ...
   [178.14014 160.79443 134.90967]
   [191.88477 183.8457  170.86523]
   [210.69931 211.69931 205.69931]]

  [[181.4707  179.4707  167.4707 ]
   [175.79027 173.79027 161.79027]
   [184.09149 182.09149 170.09149]
   ..

image: [[[[181.6543   191.6543   201.6543  ]
   [181.27148  193.3457   202.6543  ]
   [180.6914   192.6543   201.      ]
   ...
   [183.1543   187.3086   195.8457  ]
   [183.6914   188.1914   195.6914  ]
   [181.8457   187.3457   195.8457  ]]

  [[181.46289  192.96289  202.46289 ]
   [180.64844  193.42578  202.5     ]
   [184.03711  192.11133  203.07422 ]
   ...
   [182.       189.       196.07422 ]
   [180.53711  187.53711  195.53711 ]
   [182.88867  187.92578  194.11133 ]]

  [[183.       193.       203.      ]
   [181.77148  193.27148  202.77148 ]
   [182.41406  194.04297  203.5     ]
   ...
   [183.14258  188.77148  195.54297 ]
   [182.04297  187.54297  196.04297 ]
   [181.22852  186.77148  194.      ]]

  ...

  [[150.22852  124.228516 108.68555 ]
   [148.58594  123.95703  107.58594 ]
   [150.54297  125.728516 107.      ]
   ...
   [153.22852  125.771484 105.85742 ]
   [153.27148  132.45703  106.271484]
   [156.72852  130.72852  107.728516]]

  [[152.5      130.42578  112.03711 ]


image: [[[[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  ...

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]]], label: [1]
image: [[[[  0.     4.     2.5 ]
   [  0.     1.5    0.5 ]
   [  1.25   2.     1.5 ]
   ...
   [  0.    72.5  111.5 ]
   [  0.25  73.   111.5 ]
   [  5.    71.   109.5 ]]

  [[  0.     2.75   1.75]
 

image: [[[[  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   ...
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]]

  [[  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   ...
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]]

  [[160.3711  160.3711  160.3711 ]
   [ 81.60382  81.60382  81.60382]
   [ 64.14844  64.14844  64.14844]
   ...
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]]

  ...

  [[  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   ...
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]]

  [[  0.        0.        0.     ]
   [  0.        0.        0.     ]
   [  0.        0.        0.     ]
   ..

image: [[[[ 78.    90.    44.  ]
   [ 77.25  90.25  44.25]
   [ 77.    90.    44.  ]
   ...
   [147.75 155.75 139.25]
   [159.5  162.5  148.  ]
   [158.   160.   146.  ]]

  [[ 79.    91.    45.  ]
   [ 74.5   87.5   41.5 ]
   [ 80.75  93.75  47.75]
   ...
   [147.5  155.5  139.  ]
   [154.5  157.5  143.  ]
   [157.25 159.25 145.25]]

  [[ 79.75  91.75  45.75]
   [ 79.5   92.75  46.  ]
   [ 81.5   95.5   45.5 ]
   ...
   [148.5  157.   136.5 ]
   [153.25 156.25 141.25]
   [154.   156.   142.  ]]

  ...

  [[ 69.5   69.5   43.5 ]
   [ 63.75  67.25  35.25]
   [ 65.5   69.5   34.5 ]
   ...
   [ 77.25  87.25  60.25]
   [ 76.25  86.25  59.25]
   [ 75.75  85.75  58.75]]

  [[ 63.    63.    36.  ]
   [ 58.    62.    29.  ]
   [ 57.    63.5   29.5 ]
   ...
   [ 75.    85.    58.  ]
   [ 71.    81.    54.  ]
   [ 73.5   83.5   56.5 ]]

  [[ 56.75  56.75  29.75]
   [ 54.25  58.25  25.25]
   [ 51.75  58.25  24.25]
   ...
   [ 73.25  83.25  56.25]
   [ 71.25  81.25  54.25]
   [ 71.25  81.25  54.25

image: [[[[ 42.5   39.5   30.5 ]
   [ 40.75  37.75  28.75]
   [ 38.5   35.5   26.5 ]
   ...
   [114.   130.   117.  ]
   [114.   130.   117.  ]
   [114.   130.   117.  ]]

  [[ 45.25  42.25  33.25]
   [ 45.25  42.25  33.25]
   [ 35.75  32.75  23.75]
   ...
   [111.   129.   115.  ]
   [112.   128.   115.  ]
   [112.   128.   115.  ]]

  [[ 49.25  46.25  37.25]
   [ 49.5   46.5   37.5 ]
   [ 39.75  36.75  27.75]
   ...
   [108.5  126.5  112.5 ]
   [109.5  125.5  112.5 ]
   [109.5  125.5  112.5 ]]

  ...

  [[ 50.75  52.75  47.75]
   [ 51.    53.    48.  ]
   [ 52.    54.    49.  ]
   ...
   [ 39.75  40.75  35.75]
   [ 38.25  39.25  34.25]
   [ 37.75  38.75  33.75]]

  [[ 49.    51.    46.  ]
   [ 50.75  52.75  47.75]
   [ 51.75  53.75  48.75]
   ...
   [ 39.75  40.75  35.75]
   [ 38.25  39.25  34.25]
   [ 37.75  38.75  33.75]]

  [[ 45.5   47.5   42.5 ]
   [ 46.5   48.5   43.5 ]
   [ 45.5   47.5   42.5 ]
   ...
   [ 39.75  40.75  35.75]
   [ 38.25  39.25  34.25]
   [ 37.75  38.75  33.75

image: [[[[233.80714   74.264175  48.584488]
   [232.89365   78.11284   48.660156]
   [232.33984   78.33984   49.      ]
   ...
   [233.66016  226.33984  210.      ]
   [233.       227.       210.      ]
   [231.85301  225.33984  208.33984 ]]

  [[234.        75.01518   47.      ]
   [233.        78.        47.      ]
   [233.        78.11328   50.88672 ]
   ...
   [233.       227.       210.      ]
   [233.       227.       210.      ]
   [232.       226.       209.      ]]

  [[233.84431   77.69922   47.23381 ]
   [233.69922   78.        48.367188]
   [233.        79.        49.62001 ]
   ...
   [233.       227.       210.      ]
   [231.       227.       212.      ]
   [230.       226.       210.76619 ]]

  ...

  [[240.77734  207.       131.      ]
   [240.       206.       134.      ]
   [240.       207.       135.      ]
   ...
   [220.88672  221.88672  222.88672 ]
   [220.       221.       222.      ]
   [220.       221.       222.      ]]

  [[241.98047  206.01953  129.03906 ]


image: [[[[14.       35.       54.      ]
   [11.875    34.875    50.875   ]
   [12.59375  38.59375  55.59375 ]
   ...
   [ 9.046875 22.046875 38.046875]
   [ 9.546875 21.546875 37.546875]
   [ 8.765625 21.765625 37.765625]]

  [[11.09375  35.453125 51.      ]
   [13.       36.       52.      ]
   [13.46875  35.703125 56.      ]
   ...
   [ 8.234375 21.234375 38.234375]
   [ 9.234375 22.234375 39.234375]
   [ 8.453125 21.453125 37.828125]]

  [[14.078125 35.078125 54.078125]
   [11.765625 37.765625 54.765625]
   [16.328125 40.453125 56.828125]
   ...
   [ 8.984375 21.984375 38.984375]
   [ 9.       22.       39.      ]
   [ 8.625    21.625    37.625   ]]

  ...

  [[ 2.703125  7.703125 13.703125]
   [ 4.375     9.375    15.375   ]
   [ 2.609375  6.359375 12.984375]
   ...
   [34.90625  35.515625  6.390625]
   [31.15625  29.15625   4.15625 ]
   [25.78125  27.78125   3.78125 ]]

  [[ 3.171875  7.171875 16.171875]
   [ 2.65625   9.65625  15.65625 ]
   [ 3.34375   9.640625 17.875   ]
   ..

image: [[[[103.64453   94.64453   65.64453 ]
   [ 95.100586  86.100586  55.100586]
   [113.94531  106.94531   77.94531 ]
   ...
   [150.13379  146.13379  119.13379 ]
   [160.4082   155.4082   126.4082  ]
   [148.16699  143.16699  114.16699 ]]

  [[110.2832   101.2832    72.2832  ]
   [ 89.04004   80.04004   49.04004 ]
   [100.487305  93.487305  64.487305]
   ...
   [139.08594  135.08594  108.08594 ]
   [131.6836   121.68359   94.68359 ]
   [144.60547  134.60547  107.60547 ]]

  [[112.052734 103.052734  72.052734]
   [ 98.44531   89.44531   58.445312]
   [111.82031  102.82031   69.82031 ]
   ...
   [132.33301  128.33301   99.33301 ]
   [151.81348  149.75879  122.11035 ]
   [149.79688  147.09375  122.09375 ]]

  ...

  [[ 73.793945  32.66211   30.24707 ]
   [ 33.69629   21.78711   38.131836]
   [ 92.17676   51.12207   47.71582 ]
   ...
   [108.81738   99.81738   70.81738 ]
   [106.975586  97.975586  68.975586]
   [102.115234  93.115234  64.115234]]

  [[ 83.15137   36.901367  31.276367]


image: [[[[4.11562500e+01 1.35437500e+02 2.26562500e+02]
   [4.08081055e+01 1.35089355e+02 2.23651855e+02]
   [3.99541016e+01 1.36195801e+02 2.24382324e+02]
   ...
   [6.22905273e+01 1.38235352e+02 2.05657227e+02]
   [6.03481445e+01 1.40089355e+02 2.06000000e+02]
   [6.00327148e+01 1.44313965e+02 2.09061035e+02]]

  [[4.50000000e+01 1.36000000e+02 2.25000000e+02]
   [4.40312500e+01 1.36484375e+02 2.25000000e+02]
   [4.30219727e+01 1.38674805e+02 2.25837402e+02]
   ...
   [7.87407227e+01 1.49353516e+02 2.05575195e+02]
   [8.49687500e+01 1.51176758e+02 2.03252441e+02]
   [7.30224609e+01 1.50129395e+02 2.04187500e+02]]

  [[4.50000000e+01 1.37000000e+02 2.24000000e+02]
   [4.32875977e+01 1.37287598e+02 2.25000000e+02]
   [4.62861328e+01 1.38567383e+02 2.25567383e+02]
   ...
   [9.57084961e+01 1.54697754e+02 1.99567383e+02]
   [1.02415527e+02 1.61109375e+02 2.01309570e+02]
   [1.01680176e+02 1.62936523e+02 2.02610352e+02]]

  ...

  [[2.58281250e+01 2.48281250e+01 3.82812500e+00]
   [3.370

image: [[[[61.605957 70.40283  59.402832]
   [58.036743 65.848145 54.38159 ]
   [73.607544 78.61536  68.8479  ]
   ...
   [31.534912 31.542725 28.296875]
   [31.108276 33.108276 30.108276]
   [29.093018 31.093018 28.093018]]

  [[67.00513  74.3678   62.570923]
   [60.099854 68.47034  55.099854]
   [60.872925 68.872925 55.86975 ]
   ...
   [29.992188 31.992188 29.286743]
   [30.609375 32.609375 28.884033]
   [29.466553 31.466553 27.060303]]

  [[63.324463 70.926025 59.7229  ]
   [65.46643  73.46643  62.661743]
   [68.91589  76.91589  62.729736]
   ...
   [30.329468 32.158936 26.682373]
   [30.65625  32.65625  27.838257]
   [30.595093 32.595093 28.43335 ]]

  ...

  [[48.63562  59.305664 42.47754 ]
   [51.162598 62.17273  44.506348]
   [50.706055 59.870117 40.870117]
   ...
   [38.96765  37.638184 32.638184]
   [34.418945 33.818848 28.314209]
   [32.570312 31.965088 27.965088]]

  [[54.54358  64.46655  46.86499 ]
   [52.36145  62.419434 45.31787 ]
   [57.66028  65.64697  49.352417]
   ..

image: [[[[50.5791   49.1416   31.360352]
   [62.48291  47.85791  32.09375 ]
   [66.26074  43.620117 29.620117]
   ...
   [53.40869  39.40869  30.408691]
   [50.703125 36.703125 27.703125]
   [58.563477 44.563477 35.563477]]

  [[42.97998  40.74414  25.91748 ]
   [56.55127  45.158203 29.606934]
   [64.211426 46.680176 32.836426]
   ...
   [52.48535  38.48535  29.485352]
   [52.34375  38.34375  29.34375 ]
   [55.78125  41.78125  32.78125 ]]

  [[43.469727 41.38086  29.222168]
   [46.818848 40.279297 26.763672]
   [49.723633 42.504883 30.504883]
   ...
   [55.925293 41.925293 32.925293]
   [51.8208   37.8208   28.8208  ]
   [56.40381  42.40381  33.40381 ]]

  ...

  [[69.25244  41.629883 30.096191]
   [70.237305 45.212402 36.095703]
   [68.34912  49.739746 27.092285]
   ...
   [48.621582 34.621582 25.621582]
   [60.434082 45.00293  36.47998 ]
   [59.513184 40.513184 33.513184]]

  [[73.15918  46.15918  37.03711 ]
   [73.34619  49.556152 43.161133]
   [66.2041   43.36035  28.984375]
   ..

image: [[[[138.         132.         118.        ]
   [141.         137.         112.        ]
   [141.         137.         112.        ]
   ...
   [183.         172.         126.29883   ]
   [180.         168.         130.        ]
   [180.         168.         130.        ]]

  [[138.         132.         118.        ]
   [141.         137.         112.        ]
   [141.         137.         112.        ]
   ...
   [183.         172.         126.29883   ]
   [183.         171.         133.        ]
   [180.         168.         130.        ]]

  [[145.         130.         109.        ]
   [148.         133.         112.        ]
   [148.         133.         112.        ]
   ...
   [187.         175.         137.        ]
   [183.         171.         133.        ]
   [183.         171.         133.        ]]

  ...

  [[ 15.           8.           2.        ]
   [ 15.           6.           9.        ]
   [  7.          11.298828     2.        ]
   ...
   [ 33.26172     15.261719 

image: [[[[ 39.242188  19.242188   0.828125]
   [ 41.        21.         2.      ]
   [ 41.        21.         2.      ]
   ...
   [ 86.       101.        87.60597 ]
   [ 84.75781   99.539276  86.13954 ]
   [ 84.17549   98.17549   84.75166 ]]

  [[ 39.242188  19.242188   0.828125]
   [ 41.        21.         2.      ]
   [ 41.        21.         2.      ]
   ...
   [ 86.       100.747604  88.747604]
   [ 84.44792   99.794266  87.17644 ]
   [ 84.30165   98.30165   85.84093 ]]

  [[ 39.242188  18.877457   0.828125]
   [ 41.        21.         2.      ]
   [ 40.991623  21.         2.      ]
   ...
   [ 86.       101.061935  89.88924 ]
   [ 84.90971  100.21333   88.21333 ]
   [ 84.93019   99.        86.88086 ]]

  ...

  [[155.89793  109.947266  77.24219 ]
   [158.09029  112.75781   80.      ]
   [159.18108  113.88924   80.07031 ]
   ...
   [217.       176.81055  171.81055 ]
   [218.97115  180.63867  175.63867 ]
   [220.51613  183.95067  179.4668  ]]

  [[156.41406  110.41406   76.94054 ]


image: [[[[226.3653   171.63287  157.36328 ]
   [ 86.51367   69.66937   68.12268 ]
   [ 82.043396  63.648865  56.37738 ]
   ...
   [202.5987   196.57227  188.94995 ]
   [155.79688  120.34589   98.31641 ]
   [143.98035  104.28308  104.585815]]

  [[243.38708  191.13708  179.85175 ]
   [129.37195   90.16156   81.90265 ]
   [152.74689   90.803406  71.6405  ]
   ...
   [165.21436  169.8628   172.95941 ]
   [171.47742  130.11359  114.53601 ]
   [163.98883  123.80133  118.766174]]

  [[254.19861  205.91632  188.1289  ]
   [185.69855  117.17328   96.55298 ]
   [205.32227  118.86719   90.330505]
   ...
   [109.81476  102.83191  117.86792 ]
   [170.638    131.0393   118.04816 ]
   [147.18597  106.998474 113.16974 ]]

  ...

  [[172.1358   111.01831   88.33954 ]
   [170.59271  104.15521   80.81146 ]
   [161.88629   90.98004   72.94879 ]
   ...
   [ 79.47333   46.521484  37.505432]
   [ 73.08502   40.085022  33.085022]
   [ 74.41138   41.411377  34.411377]]

  [[168.40198  110.99573   90.18323 ]


image: [[[[119.826965 156.94806  170.38751 ]
   [119.16876  154.11133  167.768   ]
   [122.64453  156.51099  170.45312 ]
   ...
   [ 98.43231  114.43231  128.85553 ]
   [108.292786 122.292786 131.29279 ]
   [ 99.20538  117.20538  127.20538 ]]

  [[121.10742  158.74414  174.42578 ]
   [120.51428  157.70483  171.10956 ]
   [120.111145 160.74786  172.74786 ]
   ...
   [100.71362  122.37164  130.81897 ]
   [100.930115 114.930115 127.930115]
   [ 99.79651  120.75159  129.43323 ]]

  [[122.34375  154.875    169.875   ]
   [127.1875   159.1875   174.1875  ]
   [126.811646 157.98383  171.25977 ]
   ...
   [ 98.94086  117.94086  124.94086 ]
   [103.14264  120.14264  130.14264 ]
   [ 99.65576  117.8407   127.74823 ]]

  ...

  [[ 26.514954  53.83722   70.72589 ]
   [ 83.175415 113.07196  133.63849 ]
   [ 28.92157   47.05719   71.05719 ]
   ...
   [224.65625  216.65625  195.26172 ]
   [223.40625  216.40625  198.40625 ]
   [224.53125  219.33398  200.92578 ]]

  [[ 44.5459    80.48224  108.6759  ]


image: [[[[207.        183.         57.       ]
   [205.        184.         57.       ]
   [205.        184.         57.       ]
   ...
   [208.25      193.25       66.543945 ]
   [209.        193.25       70.5      ]
   [209.        193.         71.       ]]

  [[208.        183.         56.       ]
   [207.        182.         55.       ]
   [208.        183.         56.       ]
   ...
   [208.        192.         70.       ]
   [208.        192.         70.       ]
   [209.        194.         67.       ]]

  [[206.        183.         53.       ]
   [206.        183.         53.       ]
   [206.        183.         53.       ]
   ...
   [208.        192.         70.       ]
   [208.        192.         70.       ]
   [208.        192.         70.       ]]

  ...

  [[180.        148.          1.       ]
   [180.        149.          0.       ]
   [183.        149.          0.       ]
   ...
   [192.        181.          4.4091797]
   [193.18945   180.18945     6.189453 ]
   [191.9

image: [[[[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]

  [[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]

  [[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]

  ...

  [[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]

  [[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]

  [[237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]
   ...
   [237. 160. 168.]
   [237. 160. 168.]
   [237. 160. 168.]]]], label: [1]
image: [[[[ 11.         5.        43.      ]
   [ 11.         4.        45.      ]
   [ 12.         3.        46.      ]
   ...
   [ 46.95703   64.20703  104.45703 ]
   [ 42.70703   75.95703  110.957

image: [[[[216.      215.      211.     ]
   [219.25702 218.25702 214.25702]
   [216.38153 215.38153 211.38153]
   ...
   [204.23578 199.23578 193.23578]
   [197.69373 190.69373 184.69373]
   [210.25287 203.25287 197.25287]]

  [[215.15625 214.15625 210.15625]
   [219.50543 218.50543 214.50543]
   [215.875   214.875   210.875  ]
   ...
   [216.05518 211.05518 205.05518]
   [207.71094 202.71094 196.71094]
   [213.3133  208.3133  202.3133 ]]

  [[219.70184 218.70184 214.70184]
   [222.57031 221.57031 217.57031]
   [223.44531 222.44531 218.44531]
   ...
   [197.77386 192.77386 186.77386]
   [211.54327 208.54327 201.54327]
   [212.29688 209.29688 202.29688]]

  ...

  [[180.54303 184.54303 185.54303]
   [177.32416 181.32416 182.32416]
   [179.44531 183.44531 184.44531]
   ...
   [198.40625 198.40625 198.40625]
   [193.90228 193.90228 193.90228]
   [195.71875 195.71875 195.71875]]

  [[181.53827 185.53827 186.53827]
   [182.66748 186.66748 187.66748]
   [186.18378 190.18378 191.18378]
   ..

image: [[[[223.      223.      223.     ]
   [223.      223.      223.     ]
   [223.      223.      223.     ]
   ...
   [223.      223.      223.     ]
   [223.      223.      223.     ]
   [223.      223.      223.     ]]

  [[223.      223.      225.     ]
   [223.      223.      225.     ]
   [223.      223.      223.     ]
   ...
   [223.      223.      225.     ]
   [223.      223.      225.     ]
   [223.      223.      225.     ]]

  [[222.26758 222.26758 224.26758]
   [222.26758 222.26758 224.26758]
   [222.      222.      222.     ]
   ...
   [223.      223.      225.     ]
   [223.      223.      225.     ]
   [223.      223.      225.     ]]

  ...

  [[220.      220.      220.     ]
   [220.      220.      220.     ]
   [220.      220.      220.     ]
   ...
   [221.      221.      221.     ]
   [221.      221.      221.     ]
   [221.      221.      221.     ]]

  [[221.      221.      221.     ]
   [221.      221.      221.     ]
   [221.      221.      221.     ]
   ..

image: [[[[ 95.       134.       141.      ]
   [ 96.       135.       142.      ]
   [ 96.       135.       140.      ]
   ...
   [ 91.       126.       132.      ]
   [ 91.       125.       134.      ]
   [ 90.       124.       133.      ]]

  [[ 97.       136.       141.      ]
   [ 98.       137.       142.      ]
   [ 97.       136.       141.      ]
   ...
   [ 92.078125 126.078125 135.07812 ]
   [ 91.078125 125.078125 134.07812 ]
   [ 91.078125 125.078125 134.07812 ]]

  [[ 97.       136.       141.      ]
   [ 99.       138.       143.      ]
   [ 97.       136.       141.      ]
   ...
   [ 94.       128.       137.      ]
   [ 93.       127.       136.      ]
   [ 92.       126.       135.      ]]

  ...

  [[219.64746  248.8125   244.25684 ]
   [140.87744  186.09619  181.53369 ]
   [126.       172.       172.      ]
   ...
   [228.       249.       250.      ]
   [228.       249.       250.      ]
   [228.       249.       250.      ]]

  [[138.8418   187.56104  184.59277 ]


image: [[[[146.81738  151.81738  181.81738 ]
   [148.       153.       183.      ]
   [148.88379  153.88379  183.88379 ]
   ...
   [134.       145.       167.      ]
   [138.       146.       169.      ]
   [138.       144.       168.      ]]

  [[146.13965  151.13965  181.13965 ]
   [146.79688  151.79688  181.79688 ]
   [147.       152.       182.      ]
   ...
   [138.       144.       170.      ]
   [138.       144.       168.      ]
   [138.3125   144.3125   168.3125  ]]

  [[146.6875   151.6875   181.6875  ]
   [143.39062  148.39062  178.39062 ]
   [148.67188  153.67188  183.67188 ]
   ...
   [138.4375   143.4375   172.4375  ]
   [138.       143.04199  171.91602 ]
   [138.       144.       170.      ]]

  ...

  [[  0.         0.         0.      ]
   [  0.         0.         0.      ]
   [  0.         0.         0.      ]
   ...
   [ 13.4375    29.4375    55.4375  ]
   [ 13.        40.        67.      ]
   [ 13.138672  36.13867   70.13867 ]]

  [[  0.         0.         0.      ]


image: [[[[36.960907  50.960907  26.617157 ]
   [24.385223  27.057098  20.713348 ]
   [51.03473   59.744904  34.254242 ]
   ...
   [21.246857  33.246857  21.246857 ]
   [13.565613  25.011383  17.42212  ]
   [42.60562   43.60562   35.60562  ]]

  [[55.605682  69.43817   46.945526 ]
   [22.208557  33.241974  10.425568 ]
   [64.48761   70.716125  25.197266 ]
   ...
   [13.692078  25.692078  13.692078 ]
   [10.194153  17.657043   8.268372 ]
   [39.228516  40.228516  32.228516 ]]

  [[42.731323  46.731323  30.802063 ]
   [59.0708    69.03012   31.278168 ]
   [87.95526   89.41229   46.726746 ]
   ...
   [17.509766  28.509766  14.509766 ]
   [14.910492  19.299164   7.836273 ]
   [34.40744   35.40744   27.40744  ]]

  ...

  [[20.624573  35.983948  13.187073 ]
   [22.71875   38.374664  13.406921 ]
   [20.        37.        21.       ]
   ...
   [ 6.         9.         2.       ]
   [ 5.5371094  8.537109   0.       ]
   [ 4.845703   6.845703   1.8457031]]

  [[47.089386  65.089386  27.089386 ]


image: [[[[2.3300000e+02 2.4100000e+02 2.4400000e+02]
   [2.3301602e+02 2.4301602e+02 2.4501602e+02]
   [2.3420508e+02 2.4420508e+02 2.4520508e+02]
   ...
   [2.5247269e+02 2.0081128e+02 1.9461334e+02]
   [2.5009229e+02 1.6885629e+02 3.9437561e+01]
   [2.4534833e+02 5.7313080e+01 7.9149902e+01]]

  [[2.2983905e+02 2.4173282e+02 2.4145428e+02]
   [2.2800000e+02 2.3900000e+02 2.4300000e+02]
   [2.3179688e+02 2.4279688e+02 2.4479688e+02]
   ...
   [2.5354678e+02 1.9226749e+02 1.8018350e+02]
   [2.5039062e+02 1.8473157e+02 1.5387338e+02]
   [2.4733325e+02 3.5609375e+01 9.8684021e+01]]

  [[2.2263544e+02 2.3796747e+02 2.3831772e+02]
   [2.2600000e+02 2.3700000e+02 2.4100000e+02]
   [2.2405078e+02 2.3797461e+02 2.3900000e+02]
   ...
   [2.5234549e+02 1.6480453e+02 1.5337665e+02]
   [2.5485956e+02 1.6786694e+02 1.6599216e+02]
   [2.5046484e+02 1.6143991e+02 1.8675247e+02]]

  ...

  [[3.2531738e-02 3.2531738e-02 2.0325317e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 1

image: [[[[20.546875 53.546875 68.546875]
   [22.       56.       68.      ]
   [23.015625 57.015625 69.015625]
   ...
   [17.       40.       46.      ]
   [17.015625 40.015625 46.015625]
   [17.       40.       46.      ]]

  [[21.       53.       68.      ]
   [22.671875 54.671875 67.671875]
   [23.953125 55.953125 68.953125]
   ...
   [18.453125 38.453125 45.453125]
   [18.875    38.875    45.875   ]
   [19.       40.       45.      ]]

  [[20.625    52.625    67.625   ]
   [21.       53.       66.      ]
   [22.328125 54.328125 67.328125]
   ...
   [18.453125 39.453125 44.453125]
   [19.328125 40.328125 45.328125]
   [19.765625 40.765625 45.765625]]

  ...

  [[10.046875 14.046875 13.046875]
   [ 4.25     10.25      8.25    ]
   [12.96875  16.96875  17.96875 ]
   ...
   [ 3.5       3.5       1.5     ]
   [ 7.       10.640625  5.09375 ]
   [ 2.        2.        2.      ]]

  [[12.9375   18.9375   18.9375  ]
   [ 6.5      11.75     11.375   ]
   [11.9375   16.9375   19.9375  ]
   ..

image: [[[[ 53.11377    66.11377    56.452393 ]
   [ 60.743164   78.555176   64.64917  ]
   [121.034424  145.03442   132.03442  ]
   ...
   [ 27.824219   80.653564   75.79077  ]
   [ 42.94336   108.6543     91.083984 ]
   [ 41.08496   108.54834    90.31665  ]]

  [[ 97.799805   94.854004   85.10425  ]
   [105.85913   102.170166   90.2334   ]
   [ 94.76001   116.181885  103.5022   ]
   ...
   [ 36.08423    90.09326    84.99048  ]
   [ 39.24121   102.24121    83.67871  ]
   [ 58.803955  123.210205  104.991455 ]]

  [[113.33618   112.85303    98.53491  ]
   [110.461426  107.113525   90.29443  ]
   [120.3501    133.2063    122.9187   ]
   ...
   [ 53.07007   117.565186  104.55737  ]
   [ 44.160156  103.16016    83.82959  ]
   [ 38.838623  100.0083     80.97046  ]]

  ...

  [[ 11.01123    19.01123    22.01123  ]
   [  4.553467   12.553467   15.553467 ]
   [  0.71875     7.893799   10.893799 ]
   ...
   [ 25.869385   67.4834     41.299072 ]
   [ 34.304688   59.260254   36.59082  ]
   [ 38.1

image: [[[[206.       224.       243.      ]
   [206.       224.       243.      ]
   [207.0664   224.60938  243.15234 ]
   ...
   [191.       200.       211.      ]
   [188.       197.       207.      ]
   [186.82812  196.41406  207.29297 ]]

  [[191.80078  216.34375  238.13672 ]
   [196.       219.       240.      ]
   [208.35156  225.34375  243.33594 ]
   ...
   [191.       200.       211.      ]
   [188.38672  197.38672  207.51562 ]
   [185.25781  195.54297  207.44922 ]]

  [[193.16797  217.90625  239.89453 ]
   [196.       219.       240.      ]
   [206.       224.       243.      ]
   ...
   [188.       197.       207.      ]
   [183.64062  193.36719  204.09375 ]
   [181.7539   191.7539   202.85938 ]]

  ...

  [[119.46094  110.46094   63.222656]
   [121.515625 112.515625  64.8125  ]
   [127.42578  118.42578   74.42578 ]
   ...
   [ 94.25      98.75      33.5     ]
   [ 98.92969   95.33984   34.234375]
   [116.       117.47656   68.37891 ]]

  [[118.421875 108.59375   64.86328 ]


image: [[[[247.        161.         14.       ]
   [247.91406   159.91406    10.9140625]
   [241.        153.          4.       ]
   ...
   [254.        222.         61.       ]
   [253.91406   221.91406    60.914062 ]
   [255.        223.         62.       ]]

  [[247.        161.         14.       ]
   [245.        157.          8.       ]
   [241.        153.          4.       ]
   ...
   [254.        222.         61.       ]
   [253.91406   221.91406    60.914062 ]
   [255.        223.         62.       ]]

  [[244.        158.          9.       ]
   [237.63281   152.63281     0.       ]
   [235.        149.          2.       ]
   ...
   [254.        222.         61.       ]
   [254.        222.         61.       ]
   [254.        222.         61.       ]]

  ...

  [[  3.         26.         44.       ]
   [  2.         25.         43.       ]
   [  0.         21.054077   39.054077 ]
   ...
   [198.        168.        132.       ]
   [197.91406   167.91406   133.91406  ]
   [197. 

image: [[[[1.65951538e+00 1.72693176e+01 9.12329102e+00]
   [2.82089233e+00 1.70122986e+01 7.82025146e+00]
   [2.98223877e+00 1.63345032e+01 8.13351440e+00]
   ...
   [0.00000000e+00 5.65731812e+00 6.76348877e+00]
   [7.09533691e-02 6.39324951e+00 6.29296875e+00]
   [9.02343750e-01 9.78103638e+00 6.07052612e+00]]

  [[5.30923462e+00 2.19316711e+01 1.13626404e+01]
   [4.12704468e+00 1.77539673e+01 9.94729614e+00]
   [2.45422363e+00 1.64829712e+01 5.93679810e+00]
   ...
   [0.00000000e+00 4.27984619e+00 7.45312500e+00]
   [5.13702393e-01 6.21286011e+00 7.35348511e+00]
   [0.00000000e+00 9.70703125e+00 6.04425049e+00]]

  [[6.88903809e-01 1.40539551e+01 6.13351440e+00]
   [4.59704590e+00 1.83658752e+01 8.86196899e+00]
   [1.40704346e+00 1.64968872e+01 6.20104980e+00]
   ...
   [1.07940674e-01 3.50677490e+00 6.78906250e+00]
   [5.57891846e-01 5.26492310e+00 6.32672119e+00]
   [0.00000000e+00 7.04119873e+00 5.80966187e+00]]

  ...

  [[0.00000000e+00 2.00000000e+00 3.94354248e+00]
   [0.000

image: [[[[  0.        58.        58.      ]
   [  0.        60.447266  60.      ]
   [  0.        60.7738    59.7738  ]
   ...
   [154.42932  122.42932   72.25354 ]
   [156.78494  124.509766  73.509766]
   [140.24812  112.7657    65.7657  ]]

  [[  0.        58.        58.      ]
   [  0.        60.447266  60.      ]
   [  0.        62.348522  61.348522]
   ...
   [156.02148  123.52431   72.651474]
   [158.80925  125.89453   74.89453 ]
   [144.54666  114.96484   69.68598 ]]

  [[  0.        58.        58.      ]
   [  0.        60.447266  60.      ]
   [  0.        61.92383   60.92383 ]
   ...
   [160.16574  127.03139   74.90039 ]
   [160.9286   124.86046   76.      ]
   [147.96484  116.        72.48242 ]]

  ...

  [[239.5586   163.5586   103.55859 ]
   [241.52344  165.52344  105.52344 ]
   [242.60924  166.60924  106.60924 ]
   ...
   [218.84752  147.07603   89.30455 ]
   [216.61914  141.92383   85.15234 ]
   [214.61914  139.92383   83.15234 ]]

  [[237.       161.       101.      ]


image: [[[[164.71875 160.84375 132.125  ]
   [164.4375  161.28125 134.     ]
   [160.125   159.125   128.125  ]
   ...
   [195.28125 183.28125 145.28125]
   [194.71875 182.71875 144.71875]
   [196.28125 184.28125 146.28125]]

  [[163.53125 162.6875  134.6875 ]
   [165.15625 163.6875  135.84375]
   [163.15625 159.625   130.46875]
   ...
   [195.15625 183.15625 145.15625]
   [194.53125 182.53125 144.53125]
   [197.      185.      147.     ]]

  [[163.59375 159.59375 131.78125]
   [161.59375 160.59375 130.1875 ]
   [168.59375 164.78125 134.1875 ]
   ...
   [196.40625 183.59375 146.     ]
   [194.78125 182.78125 144.78125]
   [197.40625 183.40625 147.59375]]

  ...

  [[ 23.03125  36.03125  29.03125]
   [ 19.4375   30.03125  24.40625]
   [ 17.8125   27.8125   19.8125 ]
   ...
   [133.40625 146.59375 132.     ]
   [129.      137.      122.     ]
   [101.8125  100.40625  79.40625]]

  [[ 69.28125  66.90625  48.6875 ]
   [ 70.90625  69.0625   46.53125]
   [ 65.4375   60.90625  40.     ]
   ..

image: [[[[ 20.319702    30.319702    66.3197    ]
   [ 16.944702    32.714233    68.599     ]
   [ 16.62732     32.62732     68.62732   ]
   ...
   [ 21.230469    45.23047     79.23047   ]
   [ 17.9375      43.9375      80.70703   ]
   [ 21.565063    41.565063    76.334595  ]]

  [[ 18.208374    31.895874    66.895874  ]
   [ 15.978394    32.978394    62.978394  ]
   [ 16.723755    32.723755    66.06946   ]
   ...
   [ 18.415161    44.41516     78.10657   ]
   [ 20.345703    44.345703    80.3457    ]
   [ 25.033203    48.033203    80.0332    ]]

  [[ 16.603882    30.916382    65.29138   ]
   [ 15.423828    31.423828    67.42383   ]
   [ 14.91394     33.91394     65.91394   ]
   ...
   [ 21.179688    46.179688    77.17969   ]
   [ 18.9375      46.9375      83.9375    ]
   [ 21.749634    48.26367     84.20947   ]]

  ...

  [[  0.           0.           0.        ]
   [  0.           0.           0.        ]
   [  0.           0.           0.        ]
   ...
   [  0.           0.       

image: [[[[ 75.        95.        58.      ]
   [ 75.        95.        58.      ]
   [ 75.        95.        58.      ]
   ...
   [ 74.        94.        57.      ]
   [ 72.21875   92.21875   55.21875 ]
   [ 72.        92.        55.      ]]

  [[ 74.        94.        57.      ]
   [ 75.        95.        58.      ]
   [ 74.        94.        57.      ]
   ...
   [ 74.        94.        57.      ]
   [ 72.28906   92.28906   55.289062]
   [ 72.40625   92.40625   55.40625 ]]

  [[ 74.        94.        57.      ]
   [ 75.        95.        58.      ]
   [ 76.        96.        59.      ]
   ...
   [ 74.        94.        57.      ]
   [ 74.        94.        57.      ]
   [ 72.40625   92.40625   55.40625 ]]

  ...

  [[ 70.59375   84.        52.78125 ]
   [ 71.88403   78.44653   45.665283]
   [ 73.        77.        44.      ]
   ...
   [ 90.55469   89.        49.851562]
   [ 95.93506   93.        48.199463]
   [ 99.38501   96.505615  51.621582]]

  [[ 73.59375   85.1875    50.      ]


image: [[[[ 10.      56.     105.    ]
   [  9.25    55.25   104.25  ]
   [  8.5     57.25   103.    ]
   ...
   [  8.25    66.25   103.25  ]
   [  7.      67.     103.    ]
   [  3.      65.     102.    ]]

  [[  8.      58.     107.    ]
   [  8.      58.     107.    ]
   [  7.8125  58.8125 105.8125]
   ...
   [  7.25    67.25   103.25  ]
   [  3.5625  65.5625 102.5625]
   [  2.      66.     104.    ]]

  [[  6.25    59.75   107.    ]
   [  8.      60.     108.    ]
   [  8.      60.     108.    ]
   ...
   [  8.25    68.25   104.25  ]
   [  4.75    66.75   103.75  ]
   [  3.      67.     105.    ]]

  ...

  [[ 95.125  190.       7.8125]
   [ 19.0625  82.0625   2.8125]
   [ 28.875   88.875    8.75  ]
   ...
   [142.1875 187.1875 102.6875]
   [127.125  174.125   79.625 ]
   [130.5    178.5     68.375 ]]

  [[ 91.4375 169.375   22.5625]
   [ 21.5625  78.8125   3.5   ]
   [ 32.875   90.875    7.4375]
   ...
   [127.3125 179.0625  81.8125]
   [140.4375 193.375  104.4375]
   [141.8125 18

image: [[[[ 41.58203    122.58203    203.58203   ]
   [ 41.972656   124.97266    204.97266   ]
   [ 49.222656   138.22266    220.22266   ]
   ...
   [ 41.890625   133.89062    216.89062   ]
   [ 41.859375   129.85938    216.85938   ]
   [ 40.38672    126.38672    211.38672   ]]

  [[ 46.171875   127.171875   208.17188   ]
   [ 46.         127.         208.        ]
   [ 46.08203    128.08203    210.08203   ]
   ...
   [ 40.57422    132.2461     214.58984   ]
   [ 40.160156   129.16016    213.16016   ]
   [ 41.746094   127.33594    210.91797   ]]

  [[ 45.25       132.25       212.25      ]
   [ 47.410156   138.41016    217.41016   ]
   [ 50.546875   141.54688    220.54688   ]
   ...
   [ 42.433594   129.45312    214.11328   ]
   [ 43.         132.         216.        ]
   [ 41.453125   126.453125   207.45312   ]]

  ...

  [[  9.46875     93.49219    176.58203   ]
   [ 13.3828125   88.65234    170.35547   ]
   [ 22.226562   112.63281    199.17578   ]
   ...
   [ 53.           2.       

image: [[[[118.       198.       101.03125 ]
   [120.       197.       101.      ]
   [121.984375 199.98438  100.984375]
   ...
   [252.       190.        53.      ]
   [249.       192.        53.      ]
   [251.       192.        54.      ]]

  [[116.03516  197.03516  104.03516 ]
   [116.953125 197.95312  102.953125]
   [118.       198.       101.09375 ]
   ...
   [252.       190.        53.      ]
   [250.       191.        53.      ]
   [250.       191.        53.      ]]

  [[112.84766  197.6914   104.76953 ]
   [114.       197.       105.      ]
   [115.84375  197.07812  104.      ]
   ...
   [252.       190.        53.      ]
   [250.       191.        53.      ]
   [250.       191.        53.      ]]

  ...

  [[231.26953  232.26953  236.26953 ]
   [227.75     228.75     233.75    ]
   [224.40625  227.1914   233.75    ]
   ...
   [146.10156  164.60547  130.66406 ]
   [113.53516  141.47656  118.49609 ]
   [144.57031  168.24219  142.4375  ]]

  [[228.04688  231.29688  234.54688 ]


image: [[[[131.99959  110.99959   65.33162 ]
   [125.41211  106.03906   67.1582  ]
   [120.34898  102.71289   56.71289 ]
   ...
   [120.97008  105.97008   63.697887]
   [117.28752  102.28752   60.61955 ]
   [123.01419  110.01419   68.01419 ]]

  [[128.21289  107.21289   60.21289 ]
   [125.00073  107.25464   64.00195 ]
   [118.9082    99.99805   56.953125]
   ...
   [126.04678  112.95694   68.04678 ]
   [124.25341  107.37622   69.00195 ]
   [121.79338  103.00391   63.003906]]

  [[120.26882  101.931015  58.249912]
   [114.61719   97.61719   54.617188]
   [117.       100.        57.      ]
   ...
   [122.93048  105.93048   61.930485]
   [115.74609   98.74609   55.746094]
   [121.14     103.14      65.14    ]]

  ...

  [[103.86      86.86      42.859997]
   [ 97.433685  80.433685  36.76376 ]
   [111.65509   92.65509   50.015266]
   ...
   [114.33008   97.33008   53.33008 ]
   [107.61319   91.45322   48.2033  ]
   [107.828835  88.9668    47.957653]]

  [[104.        85.        43.      ]


image: [[[[163.9762   180.94646  181.58646 ]
   [ 45.822495  62.32187   59.998276]
   [ 75.903625  85.40701   79.89165 ]
   ...
   [ 72.81482  101.14998   73.38513 ]
   [ 49.98828   74.981094  78.35281 ]
   [ 55.706406  82.69708  103.7713  ]]

  [[126.43358  164.80202  167.12686 ]
   [ 92.94704   99.24031   81.73453 ]
   [ 53.84604   61.18669   54.70308 ]
   ...
   [ 46.707733  67.33116   50.076477]
   [ 45.166748  70.26019   75.592224]
   [ 58.104385  87.15517  108.59267 ]]

  [[146.90678  158.62918  127.55522 ]
   [ 72.69609  125.10623  149.87811 ]
   [ 46.48842   56.978012  52.72281 ]
   ...
   [ 54.105408  83.816345  75.94525 ]
   [ 62.339096  70.86488   83.19614 ]
   [ 62.345047 102.930725 125.42708 ]]

  ...

  [[164.82133  111.94217   95.49373 ]
   [185.43834  129.37897   96.36803 ]
   [163.62102  118.19914   71.08977 ]
   ...
   [160.38794  154.60019  143.1145  ]
   [156.60469  133.65388   71.4906  ]
   [205.94974  171.75052   82.544525]]

  [[160.52313  129.59094  113.457504]


2024-04-29 00:58:38.299825: W tensorflow/core/lib/png/png_io.cc:89] PNG warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space


image: [[[[2.07519531e-01 8.94409180e-01 1.03759766e-01]
   [2.58178711e+00 1.80157471e+01 1.17492676e+00]
   [9.65783691e+00 1.95454102e+01 8.92346191e+00]
   ...
   [0.00000000e+00 2.94213867e+00 0.00000000e+00]
   [4.80059814e+01 8.49831543e+01 4.13575439e+01]
   [4.42633057e+01 8.67360840e+01 3.41807861e+01]]

  [[4.93103027e+00 1.01165771e+01 4.10949707e+00]
   [2.16190186e+01 2.83234863e+01 1.44094238e+01]
   [1.22288818e+01 2.65623779e+01 1.00291748e+01]
   ...
   [7.51416016e+00 1.44118652e+01 7.62829590e+00]
   [5.91638184e+01 9.37153320e+01 5.32023926e+01]
   [9.79382324e+00 3.07187500e+01 8.73071289e+00]]

  [[9.28454590e+00 1.10861816e+01 8.06420898e+00]
   [1.98637695e+01 3.22496338e+01 1.63372803e+01]
   [1.51252441e+01 3.12264404e+01 1.15080566e+01]
   ...
   [3.33593750e+00 3.59387207e+00 1.62500000e+00]
   [6.28466797e+00 1.44130859e+01 7.93139648e+00]
   [1.14375000e+01 2.40906982e+01 8.70471191e+00]]

  ...

  [[1.97715332e+02 2.02582520e+02 1.93934082e+02]
   [1.874

image: [[[[178.      215.      223.     ]
   [177.66406 214.66406 222.66406]
   [177.1875  214.1875  222.1875 ]
   ...
   [175.      214.      221.     ]
   [174.41406 213.41406 220.41406]
   [175.9375  214.9375  221.9375 ]]

  [[179.3125  216.3125  224.3125 ]
   [178.17969 215.17969 223.17969]
   [177.      214.      222.     ]
   ...
   [178.3125  217.3125  224.3125 ]
   [176.07031 215.07031 222.07031]
   [177.10938 214.98438 222.54688]]

  [[176.      213.      221.     ]
   [178.05469 215.05469 223.05469]
   [177.      214.      222.     ]
   ...
   [177.      214.      222.     ]
   [180.      217.      225.     ]
   [177.0625  214.0625  222.0625 ]]

  ...

  [[  4.        8.        9.     ]
   [  3.        7.        8.     ]
   [  2.        6.        7.     ]
   ...
   [  4.        8.        7.     ]
   [  4.        8.        9.     ]
   [  3.        7.        8.     ]]

  [[  4.125     8.125     9.125  ]
   [  2.        6.        7.     ]
   [  2.        6.        7.     ]
   ..

image: [[[[224.13321 233.13321 238.13321]
   [227.94727 235.14708 240.54764]
   [227.94727 235.89453 239.05273]
   ...
   [217.6475  227.6475  229.6475 ]
   [217.06386 227.78906 231.94727]
   [216.86679 228.0666  231.85938]]

  [[222.84825 231.98888 236.91856]
   [222.26903 231.26903 236.26903]
   [220.49889 230.40718 234.95303]
   ...
   [218.20517 227.20517 232.20517]
   [218.57277 227.82243 232.6976 ]
   [219.77148 228.77148 233.77148]]

  [[220.94823 230.08885 235.01854]
   [221.58101 230.58101 235.58101]
   [219.92172 228.92172 233.92172]
   ...
   [218.      227.      232.     ]
   [218.68266 227.68266 232.68266]
   [218.38672 227.38672 232.38672]]

  ...

  [[202.29501 211.29501 218.29501]
   [205.21    214.21    221.21   ]
   [205.18059 214.18059 219.70793]
   ...
   [196.21605 203.47972 208.42503]
   [202.32599 210.58966 211.79865]
   [202.98146 209.03708 209.01854]]

  [[203.03983 212.03983 219.03983]
   [204.58008 213.58008 220.58008]
   [203.49889 214.49889 220.49889]
   ..

image: [[[[66.552185  66.552185  66.552185 ]
   [65.        65.        65.       ]
   [66.20137   66.20137   66.20137  ]
   ...
   [55.67578   59.67578   60.67578  ]
   [56.        60.        61.       ]
   [57.67578   61.67578   62.67578  ]]

  [[65.02734   65.02734   65.02734  ]
   [65.        65.        65.       ]
   [64.39589   64.39589   64.39589  ]
   ...
   [56.        60.        61.       ]
   [56.        60.        61.       ]
   [54.67578   58.67578   59.67578  ]]

  [[65.        65.        65.       ]
   [62.648438  62.648438  62.648438 ]
   [64.37891   64.37891   64.37891  ]
   ...
   [57.        61.        62.       ]
   [56.        60.        61.       ]
   [56.        60.        61.       ]]

  ...

  [[21.007248  21.007248  23.007248 ]
   [23.621094  23.621094  25.621094 ]
   [28.347656  28.347656  30.347656 ]
   ...
   [17.098618  20.85643   27.477524 ]
   [18.60411   25.60411   31.60411  ]
   [15.822861  22.310745  28.310745 ]]

  [[27.98964   27.98964   29.98964  ]


image: [[[[169.   193.   227.  ]
   [169.   193.   227.  ]
   [169.   193.   227.  ]
   ...
   [170.   194.   228.  ]
   [169.   193.   227.  ]
   [170.   194.   228.  ]]

  [[169.   193.   227.  ]
   [168.5  192.5  226.5 ]
   [169.   193.   227.  ]
   ...
   [170.   194.   228.  ]
   [170.   194.   228.  ]
   [170.   194.   228.  ]]

  [[169.   193.   227.  ]
   [168.5  192.5  226.5 ]
   [169.   193.   227.  ]
   ...
   [170.   194.   228.  ]
   [170.   194.   228.  ]
   [170.   194.   228.  ]]

  ...

  [[143.25 146.25  73.5 ]
   [180.25 161.25 102.75]
   [ 73.75  73.5   13.75]
   ...
   [121.75  86.    54.5 ]
   [106.    66.    36.5 ]
   [ 91.25  57.25  29.75]]

  [[141.5  131.    65.  ]
   [105.75  68.5   17.25]
   [ 67.    62.25  12.  ]
   ...
   [121.75  84.25  60.75]
   [ 82.25  44.25  22.25]
   [107.75  72.5   51.5 ]]

  [[135.25 115.    52.  ]
   [ 68.5   44.5   13.5 ]
   [ 71.25  54.75  15.25]
   ...
   [155.   117.5   93.  ]
   [ 68.5   32.5   10.5 ]
   [ 92.5   60.5   43.  

image: [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], label: [1]
image: [[[[112.       137.       159.      ]
   [112.       137.       159.      ]
   [113.       138.       159.75    ]
   ...
   [ 79.078125  77.328125  65.578125]
   [ 84.625     82.625     70.625   ]
   [ 89.75      87.75      75.75    ]]

  [[110.75     135.75     157.75    ]
   [111.       136.       158.      ]
   [111.25     136.25     158.      ]
   ...
   [ 79.515625  77.765625  66.015625]
   [ 83.9843

2024-04-29 00:58:40.283754: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [5]:
class_names = train_data.class_names
print(class_names)

['AiArtData', 'RealArt']


In [6]:
# Flatten the image data and convert labels to numpy arrays
X_train = np.concatenate([X for X, y in train_data], axis=0)
y_train = np.concatenate([y for X, y in train_data], axis=0)
X_test = np.concatenate([X for X, y in testing_data], axis=0)
y_test = np.concatenate([y for X, y in testing_data], axis=0)


2024-04-29 00:58:40.342266: W tensorflow/core/lib/png/png_io.cc:89] PNG warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
2024-04-29 00:58:54.778171: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-04-29 00:58:55.943420: W tensorflow/core/lib/png/png_io.cc:89] PNG warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
2024-04-29 00:59:09.337475: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-04-29 00:59:12.493766: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-04-29 00:59:15.752706: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [7]:
X_train.shape,X_test.shape

((777, 256, 256, 3), (194, 256, 256, 3))

In [8]:
y_train.shape,y_test.shape

((777,), (194,))

In [9]:
X_train = X_train/255.0
X_test = X_test/255.0
X_train, X_test

(array([[[[0.99607843, 0.99607843, 0.99607843],
          [0.99607843, 0.99607843, 0.99607843],
          [0.8       , 0.8       , 0.8       ],
          ...,
          [0.8099877 , 0.8139093 , 0.79430145],
          [0.99607843, 0.99607843, 0.9882353 ],
          [0.99607843, 0.99607843, 0.99607843]],
 
         [[0.99607843, 0.99607843, 0.99607843],
          [0.99607843, 0.99607843, 0.99607843],
          [0.8       , 0.8       , 0.8       ],
          ...,
          [0.8039216 , 0.80784315, 0.7882353 ],
          [0.99607843, 0.99607843, 0.9882353 ],
          [0.99607843, 0.99607843, 0.99607843]],
 
         [[0.99607843, 0.99607843, 0.99607843],
          [0.99607843, 0.99607843, 0.99607843],
          [0.8       , 0.8       , 0.8       ],
          ...,
          [0.8       , 0.8039216 , 0.78431374],
          [0.99607843, 0.99607843, 0.9882353 ],
          [0.99607843, 0.99607843, 0.99607843]],
 
         ...,
 
         [[0.99607843, 0.99607843, 0.99607843],
          [0.99607

In [10]:
#so,eventually,model.predict() should also be a 2d input
nsamples, nx, ny, nrgb = X_test.shape
X_test2 = X_test.reshape((nsamples,nx*ny*nrgb))

nsamples_train, nx_train, ny_train, nrgb_train = X_train.shape
X_train2 = X_train.reshape((nsamples_train,nx_train*ny_train*nrgb_train))

In [11]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train2,y_train)


y_pred=model.predict(X_test2)
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int32)

In [12]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.56      0.54      0.55       122
           1       0.26      0.28      0.27        72

    accuracy                           0.44       194
   macro avg       0.41      0.41      0.41       194
weighted avg       0.45      0.44      0.45       194



In [13]:
confusion_matrix(y_pred,y_test)

array([[66, 56],
       [52, 20]])

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train2,y_train)
y_pred_knn=knn.predict(X_test2)
y_pred_knn


array([0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int32)

In [15]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.56      0.59      0.58       111
           1       0.41      0.37      0.39        83

    accuracy                           0.50       194
   macro avg       0.48      0.48      0.48       194
weighted avg       0.49      0.50      0.50       194



In [16]:
confusion_matrix(y_pred_knn,y_test)

array([[66, 45],
       [52, 31]])

In [18]:
y_pred_knn

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int32)